import Head from 'next/head';
import Header from '../components/Header';
import Slides from '../components/Slides';
import Products from '../components/Products';

export default function Home() {
  return (
    <>
      <Head>
        <title>WebShop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Slides />
      <Products />
    </>
  )
}
